# Generated by Django 4.1.4 on 2022-12-20 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_key', picklefield.fields.PickledObjectField(editable=False)),
                ('priv_key', picklefield.fields.PickledObjectField(editable=False)),
                ('messages', models.JSONField()),
                ('user_1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1_id', related_query_name='user_1_id', to=settings.AUTH_USER_MODEL)),
                ('user_2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2_id', related_query_name='user_2_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
