# Generated by Django 4.1.4 on 2022-12-22 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_messagesmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 1, 24, 47, 235655, tzinfo=datetime.timezone.utc)),
        ),
    ]
