# Generated by Django 4.1.4 on 2023-01-04 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_messagesmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 4, 10, 37, 918253, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='messagesmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 4, 10, 37, 918253, tzinfo=datetime.timezone.utc)),
        ),
    ]
