# Generated by Django 4.1.4 on 2023-01-13 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chatmodel_last_message_alter_messagesmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='last_message',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messagesmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
