# Generated by Django 4.1.4 on 2023-01-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_messagesmodel_file_alter_chatmodel_last_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload_files/% Y/% m/% d/'),
        ),
    ]
