# Generated by Django 4.1.4 on 2023-01-14 02:52

import chat.logic.format_checker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_messagesmodel_visualized_chatmodel_visualized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='file',
            field=chat.logic.format_checker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='upload_files/'),
        ),
    ]
