# Generated by Django 4.1.4 on 2023-01-18 22:03

import chat.logic.format_checker
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_messagesmodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='last_message',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='has_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messagesmodel',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagesmodel',
            name='sended_now',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messagesmodel',
            name='file',
            field=chat.logic.format_checker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=''),
        ),
    ]
