# Generated by Django 4.1.4 on 2023-01-22 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_remove_chatmodel_last_message_chatmodel_has_new_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='has_new',
            new_name='user_1_has_new',
        ),
        migrations.RenameField(
            model_name='chatmodel',
            old_name='visualized',
            new_name='user_1_visualized',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='user_2_has_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='user_2_visualized',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
