# Generated by Django 4.1.4 on 2022-12-21 22:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistoryCallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=datetime.datetime(2022, 12, 21, 22, 54, 39, 786794, tzinfo=datetime.timezone.utc))),
                ('end', models.DateTimeField()),
                ('denied', models.BooleanField(default=False)),
                ('already_updated', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', related_query_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', related_query_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
