# Generated by Django 4.1.4 on 2022-12-22 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userhistorycallmodel_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistorycallmodel',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 0, 32, 39, 108887, tzinfo=datetime.timezone.utc)),
        ),
    ]
