# Generated by Django 4.1.4 on 2022-12-28 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userhistorycallmodel_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistorycallmodel',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 0, 12, 5, 630005, tzinfo=datetime.timezone.utc)),
        ),
    ]
