# Generated by Django 4.1.4 on 2023-01-04 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userhistorycallmodel_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistorycallmodel',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 4, 10, 38, 11999, tzinfo=datetime.timezone.utc)),
        ),
    ]
