# Generated by Django 4.1.4 on 2023-01-13 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userhistorycallmodel_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistorycallmodel',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
